export default {
  data: {
    page: 0,
    total: 197,
    list: [
      {
        weigh: 0.01,
        weight: 0.01,
        status: "ACTIVE",
        code: "44403903",
        sku: "44403903",
        cost: 200000,
        inventory: 0,
        length: null,
        width: null,
        height: null,
        product_id: 44403903,
        full_name: "Đây là một cái tên sản phẩm cực dài dài dài - (Màu) xanh",
        name: "Đây là một cái tên sản phẩm cực dài dài dài - (Màu) xanh",
        retail_prices: 250000,
        wholesale_price: 6000,
        total_tranfer: 0,
        total_available: 0,
        total_sell: 0,
        total_freeze: 221,
        total_out: 0,
        sell_perDay: 0,
        is_following: true,
        lack_for_sale: 221,
        tags: [],
        product_images: [
          "https://cache.giaohangtietkiem.vn/image/show/e30da9f8-1e61-4785-a303-6ba97e93ad98/cd90a9c0-9ebd-4ea5-afe8-99e0b0392767.jpg",
        ],
        type: 1,
        combo_products: null,
        optional_information: {
          total_new_imported: 0,
          total_imported_refund: 0,
          total_sales_products: 0,
          total_exported: 0,
          total_stored_awaiting_delivery: 0,
          total_cost: 0,
          total_order: 0,
          total_sell: 0,
          total_refund: 0,
        },
        total: 0,
        confirm_status: "CHUA_DUYET",
        attribute_product: null,
        property_system: null,
        category_id: 10,
        category_name: "Chăm sóc nhà cửa",
      },
      {
        weigh: 0.01,
        weight: 0.01,
        status: "ACTIVE",
        code: "44403903",
        sku: "44403903",
        cost: 200000,
        inventory: 0,
        length: null,
        width: null,
        height: null,
        product_id: 44403903,
        full_name: "Đây là một cái tên sản phẩm cực dài dài dài - (Màu) xanh",
        name: "Đây là một cái tên sản phẩm cực dài dài dài - (Màu) xanh",
        retail_prices: 250000,
        wholesale_price: 6000,
        total_tranfer: 0,
        total_available: 0,
        total_sell: 0,
        total_freeze: 221,
        total_out: 0,
        sell_perDay: 0,
        is_following: true,
        lack_for_sale: 221,
        tags: [],
        product_images: [
          "https://cache.giaohangtietkiem.vn/image/show/e30da9f8-1e61-4785-a303-6ba97e93ad98/cd90a9c0-9ebd-4ea5-afe8-99e0b0392767.jpg",
        ],
        type: 1,
        combo_products: null,
        optional_information: {
          total_new_imported: 0,
          total_imported_refund: 0,
          total_sales_products: 0,
          total_exported: 0,
          total_stored_awaiting_delivery: 0,
          total_cost: 0,
          total_order: 0,
          total_sell: 0,
          total_refund: 0,
        },
        total: 0,
        confirm_status: "CHUA_DUYET",
        attribute_product: null,
        property_system: null,
        category_id: 10,
        category_name: "Chăm sóc nhà cửa",
      },
      {
        weigh: 0.01,
        weight: 0.01,
        status: "ACTIVE",
        code: "44403903",
        sku: "44403903",
        cost: 200000,
        inventory: 0,
        length: null,
        width: null,
        height: null,
        product_id: 44403903,
        full_name: "Đây là một cái tên sản phẩm cực dài dài dài - (Màu) xanh",
        name: "Đây là một cái tên sản phẩm cực dài dài dài - (Màu) xanh",
        retail_prices: 250000,
        wholesale_price: 6000,
        total_tranfer: 0,
        total_available: 0,
        total_sell: 0,
        total_freeze: 221,
        total_out: 0,
        sell_perDay: 0,
        is_following: true,
        lack_for_sale: 221,
        tags: [],
        product_images: [
          "https://cache.giaohangtietkiem.vn/image/show/e30da9f8-1e61-4785-a303-6ba97e93ad98/cd90a9c0-9ebd-4ea5-afe8-99e0b0392767.jpg",
        ],
        type: 1,
        combo_products: null,
        optional_information: {
          total_new_imported: 0,
          total_imported_refund: 0,
          total_sales_products: 0,
          total_exported: 0,
          total_stored_awaiting_delivery: 0,
          total_cost: 0,
          total_order: 0,
          total_sell: 0,
          total_refund: 0,
        },
        total: 0,
        confirm_status: "CHUA_DUYET",
        attribute_product: null,
        property_system: null,
        category_id: 10,
        category_name: "Chăm sóc nhà cửa",
      },
      {
        weigh: 0.01,
        weight: 0.01,
        status: "ACTIVE",
        code: "44403903",
        sku: "44403903",
        cost: 200000,
        inventory: 0,
        length: null,
        width: null,
        height: null,
        product_id: 44403903,
        full_name: "Đây là một cái tên sản phẩm cực dài dài dài - (Màu) xanh",
        name: "Đây là một cái tên sản phẩm cực dài dài dài - (Màu) xanh",
        retail_prices: 250000,
        wholesale_price: 6000,
        total_tranfer: 0,
        total_available: 0,
        total_sell: 0,
        total_freeze: 221,
        total_out: 0,
        sell_perDay: 0,
        is_following: true,
        lack_for_sale: 221,
        tags: [],
        product_images: [
          "https://cache.giaohangtietkiem.vn/image/show/e30da9f8-1e61-4785-a303-6ba97e93ad98/cd90a9c0-9ebd-4ea5-afe8-99e0b0392767.jpg",
        ],
        type: 1,
        combo_products: null,
        optional_information: {
          total_new_imported: 0,
          total_imported_refund: 0,
          total_sales_products: 0,
          total_exported: 0,
          total_stored_awaiting_delivery: 0,
          total_cost: 0,
          total_order: 0,
          total_sell: 0,
          total_refund: 0,
        },
        total: 0,
        confirm_status: "CHUA_DUYET",
        attribute_product: null,
        property_system: null,
        category_id: 10,
        category_name: "Chăm sóc nhà cửa",
      },
      {
        weigh: 0.01,
        weight: 0.01,
        status: "ACTIVE",
        code: "44403903",
        sku: "44403903",
        cost: 200000,
        inventory: 0,
        length: null,
        width: null,
        height: null,
        product_id: 44403903,
        full_name: "Đây là một cái tên sản phẩm cực dài dài dài - (Màu) xanh",
        name: "Đây là một cái tên sản phẩm cực dài dài dài - (Màu) xanh",
        retail_prices: 250000,
        wholesale_price: 6000,
        total_tranfer: 0,
        total_available: 0,
        total_sell: 0,
        total_freeze: 221,
        total_out: 0,
        sell_perDay: 0,
        is_following: true,
        lack_for_sale: 221,
        tags: [],
        product_images: [
          "https://cache.giaohangtietkiem.vn/image/show/e30da9f8-1e61-4785-a303-6ba97e93ad98/cd90a9c0-9ebd-4ea5-afe8-99e0b0392767.jpg",
        ],
        type: 1,
        combo_products: null,
        optional_information: {
          total_new_imported: 0,
          total_imported_refund: 0,
          total_sales_products: 0,
          total_exported: 0,
          total_stored_awaiting_delivery: 0,
          total_cost: 0,
          total_order: 0,
          total_sell: 0,
          total_refund: 0,
        },
        total: 0,
        confirm_status: "CHUA_DUYET",
        attribute_product: null,
        property_system: null,
        category_id: 10,
        category_name: "Chăm sóc nhà cửa",
      },
    ],
    page_size: 25,
  },
  message: "Thành công.",
  status: 1,
};
