export default {
  message: "Thành công",
  success: true,
  data: {
    avatar:
      "https://cache.giaohangtietkiem.vn/image/show/fbba1b1b-f98d-4efb-b2a1-44b364463e4d/141db431-f588-4acc",
    code: "S14742709",
    district_id: null,
    first_address: null,
    hide_privacy_info: false,
    ignore_update_idcard: true,
    last_address: null,
    name: "Unswi.orders",
    pick_tel: null,
    province_id: null,
    sale_links: {
      facebook: [],
      instagram: [],
      zalo: [],
    },
    statistic: {
      avg_old_cus_ratio: "",
      award_reply_duration: "",
      delivered_ratio: "100%",
      lifetime: "7 tháng",
      med_prep_time: "",
      reply_ratio: "",
      total_customers: "> 10",
      total_delivered_pkgs: "< 50",
      total_products: "",
      total_satisfied: 0,
      total_unsatisfied: 0,
    },
    street_id: null,
    ward_id: null,
  },
};
